// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: loginService.proto

package com.caproject.service.loginservice;

public final class LoginServiceImpl {
  private LoginServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_airWaterTrackerService_LoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_airWaterTrackerService_LoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_airWaterTrackerService_LoginResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_airWaterTrackerService_LoginResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_airWaterTrackerService_LogoutRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_airWaterTrackerService_LogoutRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_airWaterTrackerService_LogoutResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_airWaterTrackerService_LogoutResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_airWaterTrackerService_UserInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_airWaterTrackerService_UserInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_airWaterTrackerService_UserInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_airWaterTrackerService_UserInfoResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022loginService.proto\022\026airWaterTrackerSer" +
      "vice\"2\n\014LoginRequest\022\020\n\010username\030\001 \001(\t\022\020" +
      "\n\010password\030\002 \001(\t\"3\n\rLoginResponse\022\020\n\010tic" +
      "ketId\030\001 \001(\t\022\020\n\010username\030\002 \001(\t\"!\n\rLogoutR" +
      "equest\022\020\n\010username\030\001 \001(\t\"!\n\016LogoutRespon" +
      "se\022\017\n\007message\030\001 \001(\t\"#\n\017UserInfoRequest\022\020" +
      "\n\010username\030\001 \001(\t\"C\n\020UserInfoResponse\022\020\n\010" +
      "username\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\017\n\007surname\030" +
      "\003 \001(\t2\254\002\n\014LoginService\022V\n\005login\022$.airWat" +
      "erTrackerService.LoginRequest\032%.airWater" +
      "TrackerService.LoginResponse\"\000\022Y\n\006logout" +
      "\022%.airWaterTrackerService.LogoutRequest\032" +
      "&.airWaterTrackerService.LogoutResponse\"" +
      "\000\022i\n\022getUserInformation\022\'.airWaterTracke" +
      "rService.UserInfoRequest\032(.airWaterTrack" +
      "erService.UserInfoResponse\"\000B8\n\"com.capr" +
      "oject.service.loginserviceB\020LoginService" +
      "ImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_airWaterTrackerService_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_airWaterTrackerService_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_airWaterTrackerService_LoginRequest_descriptor,
        new java.lang.String[] { "Username", "Password", });
    internal_static_airWaterTrackerService_LoginResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_airWaterTrackerService_LoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_airWaterTrackerService_LoginResponse_descriptor,
        new java.lang.String[] { "TicketId", "Username", });
    internal_static_airWaterTrackerService_LogoutRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_airWaterTrackerService_LogoutRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_airWaterTrackerService_LogoutRequest_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_airWaterTrackerService_LogoutResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_airWaterTrackerService_LogoutResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_airWaterTrackerService_LogoutResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_airWaterTrackerService_UserInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_airWaterTrackerService_UserInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_airWaterTrackerService_UserInfoRequest_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_airWaterTrackerService_UserInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_airWaterTrackerService_UserInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_airWaterTrackerService_UserInfoResponse_descriptor,
        new java.lang.String[] { "Username", "Name", "Surname", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
