// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: loginService.proto

package com.caproject.service.loginservice;

public interface LoginResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:airWaterTrackerService.LoginResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ticketId = 1;</code>
   */
  java.lang.String getTicketId();
  /**
   * <code>string ticketId = 1;</code>
   */
  com.google.protobuf.ByteString
      getTicketIdBytes();

  /**
   * <code>string username = 2;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 2;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
