// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: loginService.proto

package com.caproject.service.loginservice;

public interface LogoutRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:airWaterTrackerService.LogoutRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
