// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: loginService.proto

package com.caproject.service.loginservice;

public interface UserInfoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:airWaterTrackerService.UserInfoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string surname = 3;</code>
   */
  java.lang.String getSurname();
  /**
   * <code>string surname = 3;</code>
   */
  com.google.protobuf.ByteString
      getSurnameBytes();
}
