// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: airInformationService.proto

package com.caproject.protos;

public interface ActivateFilterResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:airWaterTrackerService.ActivateFilterResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 filterId = 1;</code>
   */
  int getFilterId();

  /**
   * <code>bool filterStatus = 2;</code>
   */
  boolean getFilterStatus();
}
