// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: airInformationService.proto

package com.caproject.protos;

public interface ActivateFilterRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:airWaterTrackerService.ActivateFilterRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string filterId = 1;</code>
   */
  java.lang.String getFilterId();
  /**
   * <code>string filterId = 1;</code>
   */
  com.google.protobuf.ByteString
      getFilterIdBytes();
}
