// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: airInformationService.proto

package com.caproject.protos;

public interface ActivateFilterResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:airWaterTrackerService.ActivateFilterResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string filterId = 1;</code>
   */
  java.lang.String getFilterId();
  /**
   * <code>string filterId = 1;</code>
   */
  com.google.protobuf.ByteString
      getFilterIdBytes();

  /**
   * <code>bool filterStatus = 2;</code>
   */
  boolean getFilterStatus();
}
