// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: airInformationService.proto

package com.caproject.protos;

public interface AirInfoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:airWaterTrackerService.AirInfoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string locationId = 1;</code>
   */
  java.lang.String getLocationId();
  /**
   * <code>string locationId = 1;</code>
   */
  com.google.protobuf.ByteString
      getLocationIdBytes();
}
