// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: airInformationService.proto

package com.caproject.protos;

/**
 * Protobuf type {@code airWaterTrackerService.AirInfoResponse}
 */
public  final class AirInfoResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:airWaterTrackerService.AirInfoResponse)
    AirInfoResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AirInfoResponse.newBuilder() to construct.
  private AirInfoResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AirInfoResponse() {
    zoneName_ = "";
    carbonMonoxideLevel_ = 0D;
    airQualityStatus_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AirInfoResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            zoneName_ = s;
            break;
          }
          case 17: {

            carbonMonoxideLevel_ = input.readDouble();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            airQualityStatus_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.caproject.protos.AirInformationServiceImpl.internal_static_airWaterTrackerService_AirInfoResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.caproject.protos.AirInformationServiceImpl.internal_static_airWaterTrackerService_AirInfoResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.caproject.protos.AirInfoResponse.class, com.caproject.protos.AirInfoResponse.Builder.class);
  }

  public static final int ZONENAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object zoneName_;
  /**
   * <code>string zoneName = 1;</code>
   */
  public java.lang.String getZoneName() {
    java.lang.Object ref = zoneName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      zoneName_ = s;
      return s;
    }
  }
  /**
   * <code>string zoneName = 1;</code>
   */
  public com.google.protobuf.ByteString
      getZoneNameBytes() {
    java.lang.Object ref = zoneName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      zoneName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CARBONMONOXIDELEVEL_FIELD_NUMBER = 2;
  private double carbonMonoxideLevel_;
  /**
   * <code>double carbonMonoxideLevel = 2;</code>
   */
  public double getCarbonMonoxideLevel() {
    return carbonMonoxideLevel_;
  }

  public static final int AIRQUALITYSTATUS_FIELD_NUMBER = 3;
  private volatile java.lang.Object airQualityStatus_;
  /**
   * <code>string airQualityStatus = 3;</code>
   */
  public java.lang.String getAirQualityStatus() {
    java.lang.Object ref = airQualityStatus_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      airQualityStatus_ = s;
      return s;
    }
  }
  /**
   * <code>string airQualityStatus = 3;</code>
   */
  public com.google.protobuf.ByteString
      getAirQualityStatusBytes() {
    java.lang.Object ref = airQualityStatus_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      airQualityStatus_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getZoneNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, zoneName_);
    }
    if (carbonMonoxideLevel_ != 0D) {
      output.writeDouble(2, carbonMonoxideLevel_);
    }
    if (!getAirQualityStatusBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, airQualityStatus_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getZoneNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, zoneName_);
    }
    if (carbonMonoxideLevel_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, carbonMonoxideLevel_);
    }
    if (!getAirQualityStatusBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, airQualityStatus_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.caproject.protos.AirInfoResponse)) {
      return super.equals(obj);
    }
    com.caproject.protos.AirInfoResponse other = (com.caproject.protos.AirInfoResponse) obj;

    boolean result = true;
    result = result && getZoneName()
        .equals(other.getZoneName());
    result = result && (
        java.lang.Double.doubleToLongBits(getCarbonMonoxideLevel())
        == java.lang.Double.doubleToLongBits(
            other.getCarbonMonoxideLevel()));
    result = result && getAirQualityStatus()
        .equals(other.getAirQualityStatus());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ZONENAME_FIELD_NUMBER;
    hash = (53 * hash) + getZoneName().hashCode();
    hash = (37 * hash) + CARBONMONOXIDELEVEL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getCarbonMonoxideLevel()));
    hash = (37 * hash) + AIRQUALITYSTATUS_FIELD_NUMBER;
    hash = (53 * hash) + getAirQualityStatus().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.caproject.protos.AirInfoResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.caproject.protos.AirInfoResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.caproject.protos.AirInfoResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.caproject.protos.AirInfoResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.caproject.protos.AirInfoResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.caproject.protos.AirInfoResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.caproject.protos.AirInfoResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.caproject.protos.AirInfoResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.caproject.protos.AirInfoResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.caproject.protos.AirInfoResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.caproject.protos.AirInfoResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.caproject.protos.AirInfoResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.caproject.protos.AirInfoResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code airWaterTrackerService.AirInfoResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:airWaterTrackerService.AirInfoResponse)
      com.caproject.protos.AirInfoResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.caproject.protos.AirInformationServiceImpl.internal_static_airWaterTrackerService_AirInfoResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.caproject.protos.AirInformationServiceImpl.internal_static_airWaterTrackerService_AirInfoResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.caproject.protos.AirInfoResponse.class, com.caproject.protos.AirInfoResponse.Builder.class);
    }

    // Construct using com.caproject.protos.AirInfoResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      zoneName_ = "";

      carbonMonoxideLevel_ = 0D;

      airQualityStatus_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.caproject.protos.AirInformationServiceImpl.internal_static_airWaterTrackerService_AirInfoResponse_descriptor;
    }

    @java.lang.Override
    public com.caproject.protos.AirInfoResponse getDefaultInstanceForType() {
      return com.caproject.protos.AirInfoResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.caproject.protos.AirInfoResponse build() {
      com.caproject.protos.AirInfoResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.caproject.protos.AirInfoResponse buildPartial() {
      com.caproject.protos.AirInfoResponse result = new com.caproject.protos.AirInfoResponse(this);
      result.zoneName_ = zoneName_;
      result.carbonMonoxideLevel_ = carbonMonoxideLevel_;
      result.airQualityStatus_ = airQualityStatus_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.caproject.protos.AirInfoResponse) {
        return mergeFrom((com.caproject.protos.AirInfoResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.caproject.protos.AirInfoResponse other) {
      if (other == com.caproject.protos.AirInfoResponse.getDefaultInstance()) return this;
      if (!other.getZoneName().isEmpty()) {
        zoneName_ = other.zoneName_;
        onChanged();
      }
      if (other.getCarbonMonoxideLevel() != 0D) {
        setCarbonMonoxideLevel(other.getCarbonMonoxideLevel());
      }
      if (!other.getAirQualityStatus().isEmpty()) {
        airQualityStatus_ = other.airQualityStatus_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.caproject.protos.AirInfoResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.caproject.protos.AirInfoResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object zoneName_ = "";
    /**
     * <code>string zoneName = 1;</code>
     */
    public java.lang.String getZoneName() {
      java.lang.Object ref = zoneName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        zoneName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string zoneName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getZoneNameBytes() {
      java.lang.Object ref = zoneName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        zoneName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string zoneName = 1;</code>
     */
    public Builder setZoneName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      zoneName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string zoneName = 1;</code>
     */
    public Builder clearZoneName() {
      
      zoneName_ = getDefaultInstance().getZoneName();
      onChanged();
      return this;
    }
    /**
     * <code>string zoneName = 1;</code>
     */
    public Builder setZoneNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      zoneName_ = value;
      onChanged();
      return this;
    }

    private double carbonMonoxideLevel_ ;
    /**
     * <code>double carbonMonoxideLevel = 2;</code>
     */
    public double getCarbonMonoxideLevel() {
      return carbonMonoxideLevel_;
    }
    /**
     * <code>double carbonMonoxideLevel = 2;</code>
     */
    public Builder setCarbonMonoxideLevel(double value) {
      
      carbonMonoxideLevel_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double carbonMonoxideLevel = 2;</code>
     */
    public Builder clearCarbonMonoxideLevel() {
      
      carbonMonoxideLevel_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object airQualityStatus_ = "";
    /**
     * <code>string airQualityStatus = 3;</code>
     */
    public java.lang.String getAirQualityStatus() {
      java.lang.Object ref = airQualityStatus_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        airQualityStatus_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string airQualityStatus = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAirQualityStatusBytes() {
      java.lang.Object ref = airQualityStatus_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        airQualityStatus_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string airQualityStatus = 3;</code>
     */
    public Builder setAirQualityStatus(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      airQualityStatus_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string airQualityStatus = 3;</code>
     */
    public Builder clearAirQualityStatus() {
      
      airQualityStatus_ = getDefaultInstance().getAirQualityStatus();
      onChanged();
      return this;
    }
    /**
     * <code>string airQualityStatus = 3;</code>
     */
    public Builder setAirQualityStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      airQualityStatus_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:airWaterTrackerService.AirInfoResponse)
  }

  // @@protoc_insertion_point(class_scope:airWaterTrackerService.AirInfoResponse)
  private static final com.caproject.protos.AirInfoResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.caproject.protos.AirInfoResponse();
  }

  public static com.caproject.protos.AirInfoResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AirInfoResponse>
      PARSER = new com.google.protobuf.AbstractParser<AirInfoResponse>() {
    @java.lang.Override
    public AirInfoResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AirInfoResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AirInfoResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AirInfoResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.caproject.protos.AirInfoResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

