// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: airInformationService.proto

package com.caproject.protos;

public interface AirInfoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:airWaterTrackerService.AirInfoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string zoneName = 1;</code>
   */
  java.lang.String getZoneName();
  /**
   * <code>string zoneName = 1;</code>
   */
  com.google.protobuf.ByteString
      getZoneNameBytes();

  /**
   * <code>double carbonMonoxideLevel = 2;</code>
   */
  double getCarbonMonoxideLevel();

  /**
   * <code>string airQualityStatus = 3;</code>
   */
  java.lang.String getAirQualityStatus();
  /**
   * <code>string airQualityStatus = 3;</code>
   */
  com.google.protobuf.ByteString
      getAirQualityStatusBytes();
}
