// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: loginService.proto

package com.caproject.protos;

public interface LogoutResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:airWaterTrackerService.LogoutResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
