// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: radiationInformationService.proto

package com.caproject.protos;

public interface RadiationLevelResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:airWaterTrackerService.RadiationLevelResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double radiationLevel = 1;</code>
   */
  double getRadiationLevel();

  /**
   * <code>string radioactiveType = 2;</code>
   */
  java.lang.String getRadioactiveType();
  /**
   * <code>string radioactiveType = 2;</code>
   */
  com.google.protobuf.ByteString
      getRadioactiveTypeBytes();

  /**
   * <code>int32 sensorId = 3;</code>
   */
  int getSensorId();
}
