// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: radiationInformationService.proto

package com.caproject.protos;

public interface RadiationLevelRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:airWaterTrackerService.RadiationLevelRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 locationId = 1;</code>
   */
  int getLocationId();
}
