// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: radiationInformationService.proto

package com.caproject.protos;

/**
 * Protobuf type {@code airWaterTrackerService.RadiationLevelResponse}
 */
public  final class RadiationLevelResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:airWaterTrackerService.RadiationLevelResponse)
    RadiationLevelResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RadiationLevelResponse.newBuilder() to construct.
  private RadiationLevelResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RadiationLevelResponse() {
    radiationLevel_ = 0D;
    radioactiveType_ = "";
    sensorId_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RadiationLevelResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 9: {

            radiationLevel_ = input.readDouble();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            radioactiveType_ = s;
            break;
          }
          case 24: {

            sensorId_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.caproject.protos.RadiationInformationServiceImpl.internal_static_airWaterTrackerService_RadiationLevelResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.caproject.protos.RadiationInformationServiceImpl.internal_static_airWaterTrackerService_RadiationLevelResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.caproject.protos.RadiationLevelResponse.class, com.caproject.protos.RadiationLevelResponse.Builder.class);
  }

  public static final int RADIATIONLEVEL_FIELD_NUMBER = 1;
  private double radiationLevel_;
  /**
   * <code>double radiationLevel = 1;</code>
   */
  public double getRadiationLevel() {
    return radiationLevel_;
  }

  public static final int RADIOACTIVETYPE_FIELD_NUMBER = 2;
  private volatile java.lang.Object radioactiveType_;
  /**
   * <code>string radioactiveType = 2;</code>
   */
  public java.lang.String getRadioactiveType() {
    java.lang.Object ref = radioactiveType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      radioactiveType_ = s;
      return s;
    }
  }
  /**
   * <code>string radioactiveType = 2;</code>
   */
  public com.google.protobuf.ByteString
      getRadioactiveTypeBytes() {
    java.lang.Object ref = radioactiveType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      radioactiveType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SENSORID_FIELD_NUMBER = 3;
  private int sensorId_;
  /**
   * <code>int32 sensorId = 3;</code>
   */
  public int getSensorId() {
    return sensorId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (radiationLevel_ != 0D) {
      output.writeDouble(1, radiationLevel_);
    }
    if (!getRadioactiveTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, radioactiveType_);
    }
    if (sensorId_ != 0) {
      output.writeInt32(3, sensorId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (radiationLevel_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, radiationLevel_);
    }
    if (!getRadioactiveTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, radioactiveType_);
    }
    if (sensorId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, sensorId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.caproject.protos.RadiationLevelResponse)) {
      return super.equals(obj);
    }
    com.caproject.protos.RadiationLevelResponse other = (com.caproject.protos.RadiationLevelResponse) obj;

    boolean result = true;
    result = result && (
        java.lang.Double.doubleToLongBits(getRadiationLevel())
        == java.lang.Double.doubleToLongBits(
            other.getRadiationLevel()));
    result = result && getRadioactiveType()
        .equals(other.getRadioactiveType());
    result = result && (getSensorId()
        == other.getSensorId());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RADIATIONLEVEL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getRadiationLevel()));
    hash = (37 * hash) + RADIOACTIVETYPE_FIELD_NUMBER;
    hash = (53 * hash) + getRadioactiveType().hashCode();
    hash = (37 * hash) + SENSORID_FIELD_NUMBER;
    hash = (53 * hash) + getSensorId();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.caproject.protos.RadiationLevelResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.caproject.protos.RadiationLevelResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.caproject.protos.RadiationLevelResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.caproject.protos.RadiationLevelResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.caproject.protos.RadiationLevelResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.caproject.protos.RadiationLevelResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.caproject.protos.RadiationLevelResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.caproject.protos.RadiationLevelResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.caproject.protos.RadiationLevelResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.caproject.protos.RadiationLevelResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.caproject.protos.RadiationLevelResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.caproject.protos.RadiationLevelResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.caproject.protos.RadiationLevelResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code airWaterTrackerService.RadiationLevelResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:airWaterTrackerService.RadiationLevelResponse)
      com.caproject.protos.RadiationLevelResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.caproject.protos.RadiationInformationServiceImpl.internal_static_airWaterTrackerService_RadiationLevelResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.caproject.protos.RadiationInformationServiceImpl.internal_static_airWaterTrackerService_RadiationLevelResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.caproject.protos.RadiationLevelResponse.class, com.caproject.protos.RadiationLevelResponse.Builder.class);
    }

    // Construct using com.caproject.protos.RadiationLevelResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      radiationLevel_ = 0D;

      radioactiveType_ = "";

      sensorId_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.caproject.protos.RadiationInformationServiceImpl.internal_static_airWaterTrackerService_RadiationLevelResponse_descriptor;
    }

    @java.lang.Override
    public com.caproject.protos.RadiationLevelResponse getDefaultInstanceForType() {
      return com.caproject.protos.RadiationLevelResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.caproject.protos.RadiationLevelResponse build() {
      com.caproject.protos.RadiationLevelResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.caproject.protos.RadiationLevelResponse buildPartial() {
      com.caproject.protos.RadiationLevelResponse result = new com.caproject.protos.RadiationLevelResponse(this);
      result.radiationLevel_ = radiationLevel_;
      result.radioactiveType_ = radioactiveType_;
      result.sensorId_ = sensorId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.caproject.protos.RadiationLevelResponse) {
        return mergeFrom((com.caproject.protos.RadiationLevelResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.caproject.protos.RadiationLevelResponse other) {
      if (other == com.caproject.protos.RadiationLevelResponse.getDefaultInstance()) return this;
      if (other.getRadiationLevel() != 0D) {
        setRadiationLevel(other.getRadiationLevel());
      }
      if (!other.getRadioactiveType().isEmpty()) {
        radioactiveType_ = other.radioactiveType_;
        onChanged();
      }
      if (other.getSensorId() != 0) {
        setSensorId(other.getSensorId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.caproject.protos.RadiationLevelResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.caproject.protos.RadiationLevelResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private double radiationLevel_ ;
    /**
     * <code>double radiationLevel = 1;</code>
     */
    public double getRadiationLevel() {
      return radiationLevel_;
    }
    /**
     * <code>double radiationLevel = 1;</code>
     */
    public Builder setRadiationLevel(double value) {
      
      radiationLevel_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double radiationLevel = 1;</code>
     */
    public Builder clearRadiationLevel() {
      
      radiationLevel_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object radioactiveType_ = "";
    /**
     * <code>string radioactiveType = 2;</code>
     */
    public java.lang.String getRadioactiveType() {
      java.lang.Object ref = radioactiveType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        radioactiveType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string radioactiveType = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRadioactiveTypeBytes() {
      java.lang.Object ref = radioactiveType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        radioactiveType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string radioactiveType = 2;</code>
     */
    public Builder setRadioactiveType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      radioactiveType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string radioactiveType = 2;</code>
     */
    public Builder clearRadioactiveType() {
      
      radioactiveType_ = getDefaultInstance().getRadioactiveType();
      onChanged();
      return this;
    }
    /**
     * <code>string radioactiveType = 2;</code>
     */
    public Builder setRadioactiveTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      radioactiveType_ = value;
      onChanged();
      return this;
    }

    private int sensorId_ ;
    /**
     * <code>int32 sensorId = 3;</code>
     */
    public int getSensorId() {
      return sensorId_;
    }
    /**
     * <code>int32 sensorId = 3;</code>
     */
    public Builder setSensorId(int value) {
      
      sensorId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 sensorId = 3;</code>
     */
    public Builder clearSensorId() {
      
      sensorId_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:airWaterTrackerService.RadiationLevelResponse)
  }

  // @@protoc_insertion_point(class_scope:airWaterTrackerService.RadiationLevelResponse)
  private static final com.caproject.protos.RadiationLevelResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.caproject.protos.RadiationLevelResponse();
  }

  public static com.caproject.protos.RadiationLevelResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RadiationLevelResponse>
      PARSER = new com.google.protobuf.AbstractParser<RadiationLevelResponse>() {
    @java.lang.Override
    public RadiationLevelResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RadiationLevelResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RadiationLevelResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RadiationLevelResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.caproject.protos.RadiationLevelResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

