// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: waterInformationService.proto

package com.caproject.protos;

public interface WaterPhResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:airWaterTrackerService.WaterPhResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double phValue = 1;</code>
   */
  double getPhValue();

  /**
   * <code>double drinkability = 2;</code>
   */
  double getDrinkability();
}
