// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: waterInformationService.proto

package com.caproject.protos;

/**
 * Protobuf type {@code airWaterTrackerService.WaterPhResponse}
 */
public  final class WaterPhResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:airWaterTrackerService.WaterPhResponse)
    WaterPhResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WaterPhResponse.newBuilder() to construct.
  private WaterPhResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WaterPhResponse() {
    phValue_ = 0D;
    drinkability_ = 0D;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WaterPhResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 9: {

            phValue_ = input.readDouble();
            break;
          }
          case 17: {

            drinkability_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.caproject.protos.WaterInformationServiceImpl.internal_static_airWaterTrackerService_WaterPhResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.caproject.protos.WaterInformationServiceImpl.internal_static_airWaterTrackerService_WaterPhResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.caproject.protos.WaterPhResponse.class, com.caproject.protos.WaterPhResponse.Builder.class);
  }

  public static final int PHVALUE_FIELD_NUMBER = 1;
  private double phValue_;
  /**
   * <code>double phValue = 1;</code>
   */
  public double getPhValue() {
    return phValue_;
  }

  public static final int DRINKABILITY_FIELD_NUMBER = 2;
  private double drinkability_;
  /**
   * <code>double drinkability = 2;</code>
   */
  public double getDrinkability() {
    return drinkability_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (phValue_ != 0D) {
      output.writeDouble(1, phValue_);
    }
    if (drinkability_ != 0D) {
      output.writeDouble(2, drinkability_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (phValue_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, phValue_);
    }
    if (drinkability_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, drinkability_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.caproject.protos.WaterPhResponse)) {
      return super.equals(obj);
    }
    com.caproject.protos.WaterPhResponse other = (com.caproject.protos.WaterPhResponse) obj;

    boolean result = true;
    result = result && (
        java.lang.Double.doubleToLongBits(getPhValue())
        == java.lang.Double.doubleToLongBits(
            other.getPhValue()));
    result = result && (
        java.lang.Double.doubleToLongBits(getDrinkability())
        == java.lang.Double.doubleToLongBits(
            other.getDrinkability()));
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PHVALUE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getPhValue()));
    hash = (37 * hash) + DRINKABILITY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getDrinkability()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.caproject.protos.WaterPhResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.caproject.protos.WaterPhResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.caproject.protos.WaterPhResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.caproject.protos.WaterPhResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.caproject.protos.WaterPhResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.caproject.protos.WaterPhResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.caproject.protos.WaterPhResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.caproject.protos.WaterPhResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.caproject.protos.WaterPhResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.caproject.protos.WaterPhResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.caproject.protos.WaterPhResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.caproject.protos.WaterPhResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.caproject.protos.WaterPhResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code airWaterTrackerService.WaterPhResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:airWaterTrackerService.WaterPhResponse)
      com.caproject.protos.WaterPhResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.caproject.protos.WaterInformationServiceImpl.internal_static_airWaterTrackerService_WaterPhResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.caproject.protos.WaterInformationServiceImpl.internal_static_airWaterTrackerService_WaterPhResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.caproject.protos.WaterPhResponse.class, com.caproject.protos.WaterPhResponse.Builder.class);
    }

    // Construct using com.caproject.protos.WaterPhResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      phValue_ = 0D;

      drinkability_ = 0D;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.caproject.protos.WaterInformationServiceImpl.internal_static_airWaterTrackerService_WaterPhResponse_descriptor;
    }

    @java.lang.Override
    public com.caproject.protos.WaterPhResponse getDefaultInstanceForType() {
      return com.caproject.protos.WaterPhResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.caproject.protos.WaterPhResponse build() {
      com.caproject.protos.WaterPhResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.caproject.protos.WaterPhResponse buildPartial() {
      com.caproject.protos.WaterPhResponse result = new com.caproject.protos.WaterPhResponse(this);
      result.phValue_ = phValue_;
      result.drinkability_ = drinkability_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.caproject.protos.WaterPhResponse) {
        return mergeFrom((com.caproject.protos.WaterPhResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.caproject.protos.WaterPhResponse other) {
      if (other == com.caproject.protos.WaterPhResponse.getDefaultInstance()) return this;
      if (other.getPhValue() != 0D) {
        setPhValue(other.getPhValue());
      }
      if (other.getDrinkability() != 0D) {
        setDrinkability(other.getDrinkability());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.caproject.protos.WaterPhResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.caproject.protos.WaterPhResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private double phValue_ ;
    /**
     * <code>double phValue = 1;</code>
     */
    public double getPhValue() {
      return phValue_;
    }
    /**
     * <code>double phValue = 1;</code>
     */
    public Builder setPhValue(double value) {
      
      phValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double phValue = 1;</code>
     */
    public Builder clearPhValue() {
      
      phValue_ = 0D;
      onChanged();
      return this;
    }

    private double drinkability_ ;
    /**
     * <code>double drinkability = 2;</code>
     */
    public double getDrinkability() {
      return drinkability_;
    }
    /**
     * <code>double drinkability = 2;</code>
     */
    public Builder setDrinkability(double value) {
      
      drinkability_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double drinkability = 2;</code>
     */
    public Builder clearDrinkability() {
      
      drinkability_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:airWaterTrackerService.WaterPhResponse)
  }

  // @@protoc_insertion_point(class_scope:airWaterTrackerService.WaterPhResponse)
  private static final com.caproject.protos.WaterPhResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.caproject.protos.WaterPhResponse();
  }

  public static com.caproject.protos.WaterPhResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WaterPhResponse>
      PARSER = new com.google.protobuf.AbstractParser<WaterPhResponse>() {
    @java.lang.Override
    public WaterPhResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WaterPhResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WaterPhResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WaterPhResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.caproject.protos.WaterPhResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

