// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: waterInformationService.proto

package com.caproject.protos;

public interface WaterPhInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:airWaterTrackerService.WaterPhInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string waterSupply = 1;</code>
   */
  java.lang.String getWaterSupply();
  /**
   * <code>string waterSupply = 1;</code>
   */
  com.google.protobuf.ByteString
      getWaterSupplyBytes();

  /**
   * <code>double phValue = 2;</code>
   */
  double getPhValue();

  /**
   * <code>double drinkability = 3;</code>
   */
  double getDrinkability();
}
