// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: waterInformationService.proto

package com.caproject.protos;

public interface WaterInformationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:airWaterTrackerService.WaterInformationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double coliLevel = 1;</code>
   */
  double getColiLevel();

  /**
   * <code>double drinkability = 2;</code>
   */
  double getDrinkability();
}
