// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: waterInformationService.proto

package com.caproject.protos;

public final class WaterInformationServiceImpl {
  private WaterInformationServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_airWaterTrackerService_WaterInformationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_airWaterTrackerService_WaterInformationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_airWaterTrackerService_WaterInformationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_airWaterTrackerService_WaterInformationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_airWaterTrackerService_WaterPhRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_airWaterTrackerService_WaterPhRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_airWaterTrackerService_WaterPhResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_airWaterTrackerService_WaterPhResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_airWaterTrackerService_WaterPhInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_airWaterTrackerService_WaterPhInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035waterInformationService.proto\022\026airWate" +
      "rTrackerService\"<\n\027WaterInformationReque" +
      "st\022\022\n\nlocationId\030\001 \001(\005\022\r\n\005depth\030\002 \001(\005\"C\n" +
      "\030WaterInformationResponse\022\021\n\tcoliLevel\030\001" +
      " \001(\001\022\024\n\014drinkability\030\002 \001(\001\"7\n\016WaterPhReq" +
      "uest\022\022\n\nlocationId\030\001 \001(\005\022\021\n\twaterType\030\002 " +
      "\001(\005\"E\n\017WaterPhResponse\0222\n\005items\030\001 \003(\0132#." +
      "airWaterTrackerService.WaterPhInfo\"I\n\013Wa" +
      "terPhInfo\022\023\n\013waterSupply\030\001 \001(\t\022\017\n\007phValu" +
      "e\030\002 \001(\001\022\024\n\014drinkability\030\003 \001(\0012\375\001\n\027WaterI" +
      "nformationService\022z\n\023GetWaterInformation" +
      "\022/.airWaterTrackerService.WaterInformati" +
      "onRequest\0320.airWaterTrackerService.Water" +
      "InformationResponse\"\000\022f\n\017GetWaterPhValue" +
      "\022&.airWaterTrackerService.WaterPhRequest" +
      "\032\'.airWaterTrackerService.WaterPhRespons" +
      "e\"\000(\001B5\n\024com.caproject.protosB\033WaterInfo" +
      "rmationServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_airWaterTrackerService_WaterInformationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_airWaterTrackerService_WaterInformationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_airWaterTrackerService_WaterInformationRequest_descriptor,
        new java.lang.String[] { "LocationId", "Depth", });
    internal_static_airWaterTrackerService_WaterInformationResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_airWaterTrackerService_WaterInformationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_airWaterTrackerService_WaterInformationResponse_descriptor,
        new java.lang.String[] { "ColiLevel", "Drinkability", });
    internal_static_airWaterTrackerService_WaterPhRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_airWaterTrackerService_WaterPhRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_airWaterTrackerService_WaterPhRequest_descriptor,
        new java.lang.String[] { "LocationId", "WaterType", });
    internal_static_airWaterTrackerService_WaterPhResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_airWaterTrackerService_WaterPhResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_airWaterTrackerService_WaterPhResponse_descriptor,
        new java.lang.String[] { "Items", });
    internal_static_airWaterTrackerService_WaterPhInfo_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_airWaterTrackerService_WaterPhInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_airWaterTrackerService_WaterPhInfo_descriptor,
        new java.lang.String[] { "WaterSupply", "PhValue", "Drinkability", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
