// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: waterInformationService.proto

package com.caproject.protos;

public interface WaterPhRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:airWaterTrackerService.WaterPhRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 locationId = 1;</code>
   */
  int getLocationId();

  /**
   * <code>int32 waterType = 2;</code>
   */
  int getWaterType();
}
