// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: waterInformationService.proto

package com.caproject.protos;

public interface WaterInformationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:airWaterTrackerService.WaterInformationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 locationId = 1;</code>
   */
  int getLocationId();

  /**
   * <code>int32 depth = 2;</code>
   */
  int getDepth();
}
