// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: waterInformationService.proto

package com.caproject.protos;

public interface WaterPhResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:airWaterTrackerService.WaterPhResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .airWaterTrackerService.WaterPhInfo items = 1;</code>
   */
  java.util.List<com.caproject.protos.WaterPhInfo> 
      getItemsList();
  /**
   * <code>repeated .airWaterTrackerService.WaterPhInfo items = 1;</code>
   */
  com.caproject.protos.WaterPhInfo getItems(int index);
  /**
   * <code>repeated .airWaterTrackerService.WaterPhInfo items = 1;</code>
   */
  int getItemsCount();
  /**
   * <code>repeated .airWaterTrackerService.WaterPhInfo items = 1;</code>
   */
  java.util.List<? extends com.caproject.protos.WaterPhInfoOrBuilder> 
      getItemsOrBuilderList();
  /**
   * <code>repeated .airWaterTrackerService.WaterPhInfo items = 1;</code>
   */
  com.caproject.protos.WaterPhInfoOrBuilder getItemsOrBuilder(
      int index);
}
