// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: waterInformationService.proto

package com.caproject.protos;

/**
 * Protobuf type {@code airWaterTrackerService.WaterPhInfo}
 */
public  final class WaterPhInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:airWaterTrackerService.WaterPhInfo)
    WaterPhInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WaterPhInfo.newBuilder() to construct.
  private WaterPhInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WaterPhInfo() {
    waterSupply_ = "";
    phValue_ = 0D;
    drinkability_ = 0D;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WaterPhInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            waterSupply_ = s;
            break;
          }
          case 17: {

            phValue_ = input.readDouble();
            break;
          }
          case 25: {

            drinkability_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.caproject.protos.WaterInformationServiceImpl.internal_static_airWaterTrackerService_WaterPhInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.caproject.protos.WaterInformationServiceImpl.internal_static_airWaterTrackerService_WaterPhInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.caproject.protos.WaterPhInfo.class, com.caproject.protos.WaterPhInfo.Builder.class);
  }

  public static final int WATERSUPPLY_FIELD_NUMBER = 1;
  private volatile java.lang.Object waterSupply_;
  /**
   * <code>string waterSupply = 1;</code>
   */
  public java.lang.String getWaterSupply() {
    java.lang.Object ref = waterSupply_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      waterSupply_ = s;
      return s;
    }
  }
  /**
   * <code>string waterSupply = 1;</code>
   */
  public com.google.protobuf.ByteString
      getWaterSupplyBytes() {
    java.lang.Object ref = waterSupply_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      waterSupply_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PHVALUE_FIELD_NUMBER = 2;
  private double phValue_;
  /**
   * <code>double phValue = 2;</code>
   */
  public double getPhValue() {
    return phValue_;
  }

  public static final int DRINKABILITY_FIELD_NUMBER = 3;
  private double drinkability_;
  /**
   * <code>double drinkability = 3;</code>
   */
  public double getDrinkability() {
    return drinkability_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getWaterSupplyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, waterSupply_);
    }
    if (phValue_ != 0D) {
      output.writeDouble(2, phValue_);
    }
    if (drinkability_ != 0D) {
      output.writeDouble(3, drinkability_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getWaterSupplyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, waterSupply_);
    }
    if (phValue_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, phValue_);
    }
    if (drinkability_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, drinkability_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.caproject.protos.WaterPhInfo)) {
      return super.equals(obj);
    }
    com.caproject.protos.WaterPhInfo other = (com.caproject.protos.WaterPhInfo) obj;

    boolean result = true;
    result = result && getWaterSupply()
        .equals(other.getWaterSupply());
    result = result && (
        java.lang.Double.doubleToLongBits(getPhValue())
        == java.lang.Double.doubleToLongBits(
            other.getPhValue()));
    result = result && (
        java.lang.Double.doubleToLongBits(getDrinkability())
        == java.lang.Double.doubleToLongBits(
            other.getDrinkability()));
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + WATERSUPPLY_FIELD_NUMBER;
    hash = (53 * hash) + getWaterSupply().hashCode();
    hash = (37 * hash) + PHVALUE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getPhValue()));
    hash = (37 * hash) + DRINKABILITY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getDrinkability()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.caproject.protos.WaterPhInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.caproject.protos.WaterPhInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.caproject.protos.WaterPhInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.caproject.protos.WaterPhInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.caproject.protos.WaterPhInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.caproject.protos.WaterPhInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.caproject.protos.WaterPhInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.caproject.protos.WaterPhInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.caproject.protos.WaterPhInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.caproject.protos.WaterPhInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.caproject.protos.WaterPhInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.caproject.protos.WaterPhInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.caproject.protos.WaterPhInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code airWaterTrackerService.WaterPhInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:airWaterTrackerService.WaterPhInfo)
      com.caproject.protos.WaterPhInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.caproject.protos.WaterInformationServiceImpl.internal_static_airWaterTrackerService_WaterPhInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.caproject.protos.WaterInformationServiceImpl.internal_static_airWaterTrackerService_WaterPhInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.caproject.protos.WaterPhInfo.class, com.caproject.protos.WaterPhInfo.Builder.class);
    }

    // Construct using com.caproject.protos.WaterPhInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      waterSupply_ = "";

      phValue_ = 0D;

      drinkability_ = 0D;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.caproject.protos.WaterInformationServiceImpl.internal_static_airWaterTrackerService_WaterPhInfo_descriptor;
    }

    @java.lang.Override
    public com.caproject.protos.WaterPhInfo getDefaultInstanceForType() {
      return com.caproject.protos.WaterPhInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.caproject.protos.WaterPhInfo build() {
      com.caproject.protos.WaterPhInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.caproject.protos.WaterPhInfo buildPartial() {
      com.caproject.protos.WaterPhInfo result = new com.caproject.protos.WaterPhInfo(this);
      result.waterSupply_ = waterSupply_;
      result.phValue_ = phValue_;
      result.drinkability_ = drinkability_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.caproject.protos.WaterPhInfo) {
        return mergeFrom((com.caproject.protos.WaterPhInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.caproject.protos.WaterPhInfo other) {
      if (other == com.caproject.protos.WaterPhInfo.getDefaultInstance()) return this;
      if (!other.getWaterSupply().isEmpty()) {
        waterSupply_ = other.waterSupply_;
        onChanged();
      }
      if (other.getPhValue() != 0D) {
        setPhValue(other.getPhValue());
      }
      if (other.getDrinkability() != 0D) {
        setDrinkability(other.getDrinkability());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.caproject.protos.WaterPhInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.caproject.protos.WaterPhInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object waterSupply_ = "";
    /**
     * <code>string waterSupply = 1;</code>
     */
    public java.lang.String getWaterSupply() {
      java.lang.Object ref = waterSupply_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        waterSupply_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string waterSupply = 1;</code>
     */
    public com.google.protobuf.ByteString
        getWaterSupplyBytes() {
      java.lang.Object ref = waterSupply_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        waterSupply_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string waterSupply = 1;</code>
     */
    public Builder setWaterSupply(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      waterSupply_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string waterSupply = 1;</code>
     */
    public Builder clearWaterSupply() {
      
      waterSupply_ = getDefaultInstance().getWaterSupply();
      onChanged();
      return this;
    }
    /**
     * <code>string waterSupply = 1;</code>
     */
    public Builder setWaterSupplyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      waterSupply_ = value;
      onChanged();
      return this;
    }

    private double phValue_ ;
    /**
     * <code>double phValue = 2;</code>
     */
    public double getPhValue() {
      return phValue_;
    }
    /**
     * <code>double phValue = 2;</code>
     */
    public Builder setPhValue(double value) {
      
      phValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double phValue = 2;</code>
     */
    public Builder clearPhValue() {
      
      phValue_ = 0D;
      onChanged();
      return this;
    }

    private double drinkability_ ;
    /**
     * <code>double drinkability = 3;</code>
     */
    public double getDrinkability() {
      return drinkability_;
    }
    /**
     * <code>double drinkability = 3;</code>
     */
    public Builder setDrinkability(double value) {
      
      drinkability_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double drinkability = 3;</code>
     */
    public Builder clearDrinkability() {
      
      drinkability_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:airWaterTrackerService.WaterPhInfo)
  }

  // @@protoc_insertion_point(class_scope:airWaterTrackerService.WaterPhInfo)
  private static final com.caproject.protos.WaterPhInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.caproject.protos.WaterPhInfo();
  }

  public static com.caproject.protos.WaterPhInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WaterPhInfo>
      PARSER = new com.google.protobuf.AbstractParser<WaterPhInfo>() {
    @java.lang.Override
    public WaterPhInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WaterPhInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WaterPhInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WaterPhInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.caproject.protos.WaterPhInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

