// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: waterInformationService.proto

package com.caproject.protos;

/**
 * Protobuf type {@code airWaterTrackerService.WaterPhRequest}
 */
public  final class WaterPhRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:airWaterTrackerService.WaterPhRequest)
    WaterPhRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WaterPhRequest.newBuilder() to construct.
  private WaterPhRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WaterPhRequest() {
    locationId_ = 0;
    waterType_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WaterPhRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            locationId_ = input.readInt32();
            break;
          }
          case 16: {

            waterType_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.caproject.protos.WaterInformationServiceImpl.internal_static_airWaterTrackerService_WaterPhRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.caproject.protos.WaterInformationServiceImpl.internal_static_airWaterTrackerService_WaterPhRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.caproject.protos.WaterPhRequest.class, com.caproject.protos.WaterPhRequest.Builder.class);
  }

  public static final int LOCATIONID_FIELD_NUMBER = 1;
  private int locationId_;
  /**
   * <code>int32 locationId = 1;</code>
   */
  public int getLocationId() {
    return locationId_;
  }

  public static final int WATERTYPE_FIELD_NUMBER = 2;
  private int waterType_;
  /**
   * <code>int32 waterType = 2;</code>
   */
  public int getWaterType() {
    return waterType_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (locationId_ != 0) {
      output.writeInt32(1, locationId_);
    }
    if (waterType_ != 0) {
      output.writeInt32(2, waterType_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (locationId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, locationId_);
    }
    if (waterType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, waterType_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.caproject.protos.WaterPhRequest)) {
      return super.equals(obj);
    }
    com.caproject.protos.WaterPhRequest other = (com.caproject.protos.WaterPhRequest) obj;

    boolean result = true;
    result = result && (getLocationId()
        == other.getLocationId());
    result = result && (getWaterType()
        == other.getWaterType());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LOCATIONID_FIELD_NUMBER;
    hash = (53 * hash) + getLocationId();
    hash = (37 * hash) + WATERTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getWaterType();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.caproject.protos.WaterPhRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.caproject.protos.WaterPhRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.caproject.protos.WaterPhRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.caproject.protos.WaterPhRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.caproject.protos.WaterPhRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.caproject.protos.WaterPhRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.caproject.protos.WaterPhRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.caproject.protos.WaterPhRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.caproject.protos.WaterPhRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.caproject.protos.WaterPhRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.caproject.protos.WaterPhRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.caproject.protos.WaterPhRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.caproject.protos.WaterPhRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code airWaterTrackerService.WaterPhRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:airWaterTrackerService.WaterPhRequest)
      com.caproject.protos.WaterPhRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.caproject.protos.WaterInformationServiceImpl.internal_static_airWaterTrackerService_WaterPhRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.caproject.protos.WaterInformationServiceImpl.internal_static_airWaterTrackerService_WaterPhRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.caproject.protos.WaterPhRequest.class, com.caproject.protos.WaterPhRequest.Builder.class);
    }

    // Construct using com.caproject.protos.WaterPhRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      locationId_ = 0;

      waterType_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.caproject.protos.WaterInformationServiceImpl.internal_static_airWaterTrackerService_WaterPhRequest_descriptor;
    }

    @java.lang.Override
    public com.caproject.protos.WaterPhRequest getDefaultInstanceForType() {
      return com.caproject.protos.WaterPhRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.caproject.protos.WaterPhRequest build() {
      com.caproject.protos.WaterPhRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.caproject.protos.WaterPhRequest buildPartial() {
      com.caproject.protos.WaterPhRequest result = new com.caproject.protos.WaterPhRequest(this);
      result.locationId_ = locationId_;
      result.waterType_ = waterType_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.caproject.protos.WaterPhRequest) {
        return mergeFrom((com.caproject.protos.WaterPhRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.caproject.protos.WaterPhRequest other) {
      if (other == com.caproject.protos.WaterPhRequest.getDefaultInstance()) return this;
      if (other.getLocationId() != 0) {
        setLocationId(other.getLocationId());
      }
      if (other.getWaterType() != 0) {
        setWaterType(other.getWaterType());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.caproject.protos.WaterPhRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.caproject.protos.WaterPhRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int locationId_ ;
    /**
     * <code>int32 locationId = 1;</code>
     */
    public int getLocationId() {
      return locationId_;
    }
    /**
     * <code>int32 locationId = 1;</code>
     */
    public Builder setLocationId(int value) {
      
      locationId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 locationId = 1;</code>
     */
    public Builder clearLocationId() {
      
      locationId_ = 0;
      onChanged();
      return this;
    }

    private int waterType_ ;
    /**
     * <code>int32 waterType = 2;</code>
     */
    public int getWaterType() {
      return waterType_;
    }
    /**
     * <code>int32 waterType = 2;</code>
     */
    public Builder setWaterType(int value) {
      
      waterType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 waterType = 2;</code>
     */
    public Builder clearWaterType() {
      
      waterType_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:airWaterTrackerService.WaterPhRequest)
  }

  // @@protoc_insertion_point(class_scope:airWaterTrackerService.WaterPhRequest)
  private static final com.caproject.protos.WaterPhRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.caproject.protos.WaterPhRequest();
  }

  public static com.caproject.protos.WaterPhRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WaterPhRequest>
      PARSER = new com.google.protobuf.AbstractParser<WaterPhRequest>() {
    @java.lang.Override
    public WaterPhRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WaterPhRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WaterPhRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WaterPhRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.caproject.protos.WaterPhRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

